# Generated by Django 5.2 on 2025-04-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('unit_type', models.CharField(choices=[('adet', 'Adet'), ('kilo', 'Kilo'), ('koli', 'Koli'), ('adet-koli', 'Adet + Koli')], max_length=20)),
                ('unit_per_package', models.PositiveIntegerField(blank=True, null=True)),
                ('stock_quantity', models.FloatField(default=0)),
            ],
        ),
    ]
